services:

  ceps_web:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - ceps_db

  ceps_db:
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ceps_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  ceps_postgres_data: 